### PR TITLE
fix/FD-4084 make gauth cookie httpOnly

### PR DESCRIPTION
**Pull request by marcjasz**

### CODE REVIEW

**Comment by Haradd** [comment]
Unfortunately, I'm not able to merge it

**Comment by kamilpp** [comment]
Isn't this repository a gem like `gaming_engine`? Don't we need to bump the version to use the changes?

**Comment by marcjasz** [comment]
Version isn't defined anywhere, looks like people didn't bother. I don't think this change will require any adjustments in dependent apps

**Comment by kamilpp** [comment]
So it seems like it will automatically be included in deployments on all envs, not only int? Therefore I do not want to merge this today. Please remind me after the release

**Comment by marcjasz** [comment]
Aye, no problem

**Comment by marcjasz** [comment]
@kamilpp not sure which release you meant, but here I am

**Pull request merged**
